title: DigiPresPubs
description: A searchable index of publications related to digital preservation.
theme: just-the-docs

url: https://www.digipres.org
baseurl: /publications

# https://just-the-docs.com/docs/configuration/#callouts
callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Note
    color: yellow

aux_links:
  GitHub: https://github.com/digipres/publications

plugins:
  - jekyll-datapage-generator

# Generate pages from data:
#page_gen-dirs: true
#page_gen:
#- data: 'ipres_conferences'
#  template: 'ipres'
#  name: name
#  dir: 'ipres'

