title: DigiPresPubs
description: A searchable index of publications related to digital preservation.
theme: just-the-docs

url: https://www.digipres.org/publications/

aux_links:
  about: /about/

plugins:
  - jekyll-datapage-generator

# Generate pages from data:
page_gen-dirs: true
page_gen:
- data: 'ipres_conferences'
  template: 'ipres'
  name: name
  dir: 'ipres'