title: DigiPres Publications Index
description: A searchable index of publications related to digital preservation.
theme: just-the-docs

url: https://www.digipres.org/publications/

aux_links:
  digipres.org: https://www.digipres.org/

plugins:
  - jekyll-datapage-generator

# Generate pages from data:
page_gen:
- data: 'ipres.conferences'
  template: 'ipres'
  name: 'name'
  dir: 'ipres'