title: "DigiPres Publications Index"
homepage: https://digipres.org/publications/
description: "PROTOTYPE for a mini search engine dedicated to digital preservation."
sources:
- name: "iPRES Proceedings"
  homepage: https://www.digipres.org/publications/ipres/
  description: "An index built from the collected proceedings of the <a href=\"https://ipres-conference.org/\">iPRES conference series</a>."
  type: jsonl
  file: ./_awindex/ipres-awindex.jsonl
- name: Zenodo Digital Preservation Community
  homepage: https://zenodo.org/communities/digital-preservation
  description: "A library of openly available digital preservation reports, publications, instructions, documentations and data sets."
  type: zenodo
  community: "digital-preservation"
- name: "Awesome Digital Preservation"
  homepage: "https://github.com/digipres/awesome-digital-preservation/"
  description: "A carefully curated list of awesome digital preservation resources."
  type: awesome-list
  view_url: "https://github.com/digipres/awesome-digital-preservation/blob/main/README.md?plain=1"
  url: "https://raw.githubusercontent.com/digipres/awesome-digital-preservation/refs/heads/main/README.md"
- name: "Ethan Gates's Emulation Library"
  homepage: "https://forum.eaasi.cloud/t/emulation-resources-in-the-spn-software-preservation-bibliography/250"
  description: "A Zotero library on emulation, maintained by Ethan Gates (<a href=\"https://www.digipres.org/publications/ipres/ipres-2024/papers/using-digital-documents-to-preserve-emulation-lessons-learned-fr/\">iPRES paper</a>)."
  type: zotero
  library_type: user
  library_id: 8195999
  collection_id: "ERZIYJ3T"
- name: "Awesome Web Archiving"
  homepage: "https://github.com/iipc/awesome-web-archiving/"
  description: "An Awesome List for getting started with web archiving."
  type: awesome-list
  url: "https://raw.githubusercontent.com/iipc/awesome-web-archiving/refs/heads/main/README.md"
- name: "IIPC Web Archiving Library"
  homepage: https://netpreserve.org/about-us/resources/
  description: "The (work-in-progress) IIPC Zotero library on web archiving including IIPC conference proceedings."
  type: zotero
  library_type: group
  library_id: 2271741
