# config.yml

backend:
  #name: git-gateway
  name: github
  repo: digipres/publications
  branch: main
media_folder: "assets/uploads"

#site_url: https://www.digipres.org/publications/

collections:
- label: "Blog"
  name: "blog"
  folder: "_posts"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Featured Image", name: "thumbnail", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}

- name: ipres-conferences
  label: iPRES Conferences
  label_singular: 'iPRES Conference'
  folder: ipres
  path: '{{slug}}/index'
  slug: '{{title}}'
  filter: { field: "parent", value: "iPRES" }
  fields:
  - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'ipres' }
  - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'iPRES' }
  - { label: Title, name: title, widget: string }
  - { label: Location, name: location, widget: string }
  - { label: Dates, name: date, widget: string }
  - { label: Website, name: website, widget: string }
  - label: "Website Status"
    name: website_status
    widget: select
    options: ["active", "redirects-to-archive", "gone"]
    default: "active"
  - label: "Website Mirror (by iPRES)"
    name: website_mirror_ipres
    required: false
  - label: "Programme URL"
    name: programme_url
    required: false
  - label: "Full Proceedings As A Single Document"
    name: proceedings_full
    required: false
  - label: "Proceedings (hosted by Phaidra)"
    name: proceedings_phaidra
    required: false
  - label: "Proceedings (hosted by OSF)"
    name: proceedings_osf
    required: false
  - label: "Proceedings (hosted by IDEALS)"
    name: proceedings_ideals
    required: false
  - label: "Session Recordings URL"
    name: session_recordings
    required: false
  - {label: "Body", name: "body", widget: "markdown", required: false}

- name: 'pages'
  label: 'Pages'
  editor:
    preview: false
  files:
    - label: 'About Page'
      name: 'about'
      file: 'about.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
- name: 'config'
  label: 'Config'
  editor:
    preview: false
  files:
    - label: 'Navigation'
      name: 'navigation'
      file: '_data/navigation.yml'
      fields:
        - label: 'Navigation Items'
          name: 'items'
          widget: 'list'
          fields:
            - { label: Name, name: name, widget: string }
            - { label: Link, name: link, widget: string }