# config.yml

backend:
  #name: git-gateway
  name: github
  repo: digipres/publications
  branch: main
media_folder: "assets/uploads"

# Use the PR-based editorial workflow:
publish_mode: editorial_workflow

#site_url: https://www.digipres.org/publications/

collections:

- name: ipres-conferences
  label: iPRES Conferences
  label_singular: 'iPRES Conference'
  folder: ipres
  path: '{{slug}}/index'
  slug: '{{title}}'
  filter: { field: "parent", value: "iPRES" }
  preview_path: ipres/{{dirname}}/
  fields:
  - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'ipres' }
  - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'iPRES' }
  - { label: Title, name: title, widget: string }
  - { label: Location, name: location, widget: string }
  - { label: Dates, name: date, widget: string }
  - { label: "Logo", name: "logo", widget: "image", media_folder: "images", required: false }
  - { label: Website, name: website, widget: string }
  - label: "Website Status"
    name: website_status
    widget: select
    options: ["active", "redirects-to-archive", "gone"]
    default: "active"
  - label: "Website Mirror (by iPRES)"
    name: website_mirror_ipres
    required: false
  - label: "Programme URL"
    name: programme_url
    required: false
  - label: "Full Proceedings As A Single Document"
    name: proceedings_full
    required: false
  - label: "Proceedings (hosted by Phaidra)"
    name: proceedings_phaidra
    required: false
  - label: "Proceedings (hosted by OSF)"
    name: proceedings_osf
    required: false
  - label: "Proceedings (hosted by IDEALS)"
    name: proceedings_ideals
    required: false
  - label: "Session Recordings URL"
    name: session_recordings
    required: false
  - { label: 'Show Child Pages', name: 'has_children', widget: 'boolean', default: true, hint: "This controls whether the navigation menu includes a sub-section for the publications associated with this conference. If there are none, this can be switched off to make the menu look neater." }
  - { label: "Body", name: "body", widget: "markdown", required: false }

- name: 'pages'
  label: 'Other Pages'
  editor:
    preview: false
  files:
    - label: 'Homepage'
      name: 'index'
      file: 'index.md'
      preview_path: /
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: 'iPRES Introduction Page'
      name: 'ipres/index'
      file: 'ipres/index.md'
      preview_path: ipres/
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'iPRES' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
        - { label: 'Has Children', name: 'has_children', widget: 'hidden', default: true }
        - { label: 'Has TOC', name: 'has_toc', widget: 'hidden', default: false }
        - { label: 'Body', name: 'body', widget: 'markdown' }